# Generated by Django 5.2.8 on 2025-11-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_recipient_newsletter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={"ordering": ("-first_send_time",), "verbose_name": "рассылка", "verbose_name_plural": "рассылки"},
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="status",
            field=models.CharField(
                choices=[("created", "Создана"), ("active", "Активна"), ("completed", "Завершена")],
                default="completed",
                max_length=15,
            ),
        ),
    ]
