# Generated by Django 5.2.8 on 2026-02-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_message_owner_newsletter_owner_recipient_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("view_all_messages", "Может просматривать все сообщения")],
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "ordering": ("-start_time",),
                "permissions": [("view_all_newsletters", "Может просматривать все рассылки")],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "permissions": [("view_all_recipients", "Может просматривать всех получателей")],
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
            },
        ),
    ]
