# Generated by Django 5.2.8 on 2025-11-28 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_newsletter_options_alter_newsletter_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SendAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempt_time", models.DateTimeField(auto_now_add=True, verbose_name="Время попытки отправки")),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("fail", "Не успешно")], default="fail", max_length=15
                    ),
                ),
                ("smtp_answer", models.TextField(verbose_name="Ответ сервера")),
                (
                    "newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="core.newsletter",
                        verbose_name="рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "попытка",
                "verbose_name_plural": "попытки",
                "ordering": ("-attempt_time",),
            },
        ),
    ]
