# Generated by Django 5.2.8 on 2026-01-28 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_sendattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="sendattempt",
            name="recipient",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.recipient"
            ),
        ),
    ]
