# Generated by Django 5.2.8 on 2026-02-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_sendattempt_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="status",
            field=models.CharField(
                choices=[("created", "Создана"), ("started", "Запущена"), ("completed", "Завершена")],
                default="created",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="sendattempt",
            name="smtp_answer",
            field=models.TextField(blank=True, null=True, verbose_name="Ответ сервера"),
        ),
    ]
